INSERT INTO USER (USR_FIRST_NAME, USR_LAST_NAME, USR_EMAIL, USR_PASSWORD, USR_CREATED_DATE, USR_MODIFIED_DATE) VALUES('John', 'Doe', 'john@yandex.ru', '12345', now(), now());
INSERT INTO CATEGORY (CT_NAME, CT_DESCRIPTION) VALUES('Insurance', 'Insurance');
INSERT INTO CATEGORY (CT_NAME, CT_DESCRIPTION) VALUES('IT Services', 'IT Services');
INSERT INTO CATEGORY (CT_NAME, CT_DESCRIPTION) VALUES('Software', 'Software');
INSERT INTO CATEGORY (CT_NAME, CT_DESCRIPTION) VALUES('Hardware', 'Hardware');
INSERT INTO CATEGORY (CT_NAME, CT_DESCRIPTION) VALUES('Financial Services', 'Financial Services');
INSERT INTO CATEGORY (CT_NAME, CT_DESCRIPTION) VALUES('Construction', 'Construction');
INSERT INTO CATEGORY (CT_NAME, CT_DESCRIPTION) VALUES('Consumer Loans', 'Consumer Loans');
INSERT INTO LEAD (LD_TITLE, LD_DESCRIPTION, LD_FIRST_NAME, LD_LAST_NAME, LD_EMAIL, LD_PHONE, LD_PRICE, LD_STATUS, LD_OWNER_ID, LD_CATEGORY_ID, LD_CREATED_DATE, LD_MODIFIED_DATE ) values ('Microsoft Windows', 'OS', 'Bill', 'Gates', 'bill@microsoft.com', '555-11-22-33', 155, 'OK', 1, 3, now(), now() );